name: fastnotes_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  # Newtork
  dio: ^5.8.0+1
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Dependency Injection
  get_it: ^8.0.3
  go_router: ^16.0.0
  # UI Components
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  # Utils
  intl: ^0.20.2
  json_annotation: ^4.9.0
  # Splash Screen
  flutter_native_splash: ^2.4.6
  # External
  google_sign_in: ^6.3.0
  # Security
  flutter_dotenv: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Code Generation
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/
    - .env

flutter_native_splash:
  color: "#ffffff"  
  color_dark: "#000000"  
  # image: "assets/images/splash_image.png"
  # image_dark: "assets/images/splash_image.png"

  android_12:
    image: assets/images/splash_image.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash_image.png
    icon_background_color_dark: "#121212"

  android: true
  ios: true